import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import StoreProvider from "./StoreProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Guitar Shop",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} dark:bg-gray-900`}>
        <StoreProvider>
          <Providers>
            {children}
          </Providers>
        </StoreProvider>
      </body>
    </html>
  );
}
